services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  ARTIFACT_TARGET: /tmp/artifacts
  PGCMPHOME: /tmp/pgcmp
  PGHOST: postgres
  REGUSER: postgres
  SUPERUSER: postgres
  PGPORT: 5432
  MAHOUTHOME: /builds/cbbrowne/mahout
  PGBINDIR: /usr/bin

build1:
  stage: build
  script:
    - ./test/find-psql.sh
    - gem install org-ruby
    - git clone https://gitlab.com/cbbrowne/pgcmp.git $PGCMPHOME
    - (cd $PGCMPHOME; make all)
    - (cd test; ./test-build-stuff.sh)
    
