services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  ARTIFACT_TARGET: /tmp/artifacts
  PGCMPHOME: /tmp/pgcmp
  PGHOST: postgres
  REGUSER: postgres
  SUPERUSER: postgres
  PGPORT: 5432
  MAHOUTHOME: /builds/cbbrowne/mahout 
  PGBINDIR: /opt/gitlab/bin

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"
  - echo "PWD is ${PWD}"
  - which psql

build1:
  stage: build
  script:
    - echo $PATH
    - gem install org-ruby
    - git clone https://gitlab.com/cbbrowne/pgcmp.git $PGCMPHOME
    - (cd $PGCMPHOME; make all)
    - (cd test; ./test-build-stuff.sh)
    
