services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: runner
  POSTGRES_HOST_AUTH_METHOD: trust
  ARTIFACT_TARGET: /tmp/artifacts
  PGHOST: postgres
  REGUSER: postgres
  SUPERUSER: postgres
  PGPORT: 5432
  MAHOUTHOME: /builds/cbbrowne/mahout
  PGCMPHOME: /builds/cbbrowne/mahout/pgcmp
  PGBINDIR: /usr/lib/postgresql/12/bin
  GIT_SUBMODULE_STRATEGY: recursive
  
connect-test:
  stage: test
  image: postgres
  script:
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - which psql
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "show port;"
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "show config_file;"
    - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "show unix_socket_directories;"
    - psql -d "host=postgres user=runner port=5432 dbname=${POSTGRES_DB}" -c "select 'OK' as query_from_connstring;"
    - ls -l /var/run/postgresql

build1:
  stage: build
  script:
    - gem install org-ruby
    - make all
  
functional-test:
  stage: test
  image: postgres
  script:
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - export PGUSER=$POSTGRES_USER
    - export PGPORT=5432
    - export PGHOST=postgres
    - (cd test; ./test-build-stuff.sh)
