services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  ARTIFACT_TARGET: /tmp/artifacts
  PGCMPHOME: /tmp/pgcmp
  PGHOST: postgres
  REGUSER: postgres
  SUPERUSER: postgres
  PGPORT: 5432
  MAHOUTHOME: /builds/cbbrowne/mahout
  PGBINDIR: /usr/lib/postgresql/12/bin

build1:
  stage: build
  image: postgres
  script:
    - git clone https://gitlab.com/cbbrowne/pgcmp.git $PGCMPHOME
    - (cd test; ./test-build-stuff.sh)
    
