services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  ARTIFACT_TARGET: /tmp/artifacts
  PGHOST: postgres
  REGUSER: postgres
  SUPERUSER: postgres
  PGPORT: 5432
  MAHOUTHOME: /builds/cbbrowne/mahout
  PGCMPHOME: /builds/cbbrowne/mahout/pgcmp
  PGBINDIR: /usr/lib/postgresql/12/bin
  GIT_SUBMODULE_STRATEGY: recursive
  
build1:
  stage: build
  image: postgres
  script:
    - (cd test; ./test-build-stuff.sh)
