services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: nice_marmot
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  ARTIFACT_TARGET: /tmp/artifacts
  PGCMPHOME: /tmp/pgcmp
  PGHOST: postgres
  REGUSER: postgres
  SUPERUSER: postgres
  PGPORT: 5432
  MAHOUTHOME: /builds/cbbrowne/mahout 

build1:
  stage: build
  script:
    - echo $PATH
    - for p in $(echo $PATH | sed 's/:/ /g'); do
        if [ -e ${p}/psql ]; then
           export PGBINDIR=$p
           echo "found psql in ${p}"
        fi
      done
    - gem install org-ruby
    - git clone https://gitlab.com/cbbrowne/pgcmp.git $PGCMPHOME
    - (cd $PGCMPHOME; make all)
    - (cd test; ./test-build-stuff.sh)
    
